---
params:
  shield_key_vault_path: (( param "Please specify the location of the SHIELD agent public key in Vault" ))
  shield_ca_vault_path:  (( param "Please specify the location of the SHIELD CA certificate in Vault" ))
  shield_core_url:       (( param "Please specify the URL of your SHIELD Core" ))

releases:
- name: shield
  version: 8.0.8
  url: https://github.com/starkandwayne/shield-boshrelease/releases/download/v8.0.8/shield-8.0.8.tgz
  sha1: 55d1d6d8557f9b185fef7b5c6d73017b4c654f03
