---
params:
  shield_key_vault_path: (( param "Please specify the location of the SHIELD agent public key in Vault" ))

releases:
- name: shield
  version: 6.6.4
  url: https://bosh.io/d/github.com/starkandwayne/shield-boshrelease?v=6.6.4
  sha1: 68cd5a8adaabe4d19d4d0d69bef3577b8961c11b
