---
params:
  uaadb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  uaadb_user: uaaadmin
  uaadb_password: (( vault meta.vault "/uaadb:password" ))
  uaadb_scheme: postgresql
  uaadb_port: 5432

  ccdb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  ccdb_user: ccadmin
  ccdb_password: (( vault meta.vault "/ccdb:password" ))
  ccdb_scheme: postgres
  ccdb_port: 5432

  diegodb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  diegodb_user: diegoadmin
  diegodb_password: (( vault meta.vault "/diegodb:password" ))
  diegodb_scheme: postgres
  diegodb_port: 5432
  diegodb_connection_string: (( concat params.diegodb_scheme "://" params.diegodb_user ":" params.diegodb_password "@" params.diegodb_host ":" params.diegodb_port "/" params.diegodb_name ))
