---
instance_groups:
- name: consul_etcd
  jobs:
    - name: consul_agent
      release: consul
      consumes:
        consul_common: {from: consul_common_link}
        consul_server: {from: consul_server_link}
        consul_client: {from: consul_client_link}
      provides:
        consul_common: {as: consul_common_link, shared: true}
        consul_server: {as: consul_server_link, shared: true}
        consul_client: {as: consul_client_link, shared: true}
      properties:
        consul:
          agent:
            rewrite_resolv: false
            log_level: (( grab params.log_level ))
            mode: server
            domain: cf.internal

          .: (( inject meta.certs.consul.server ))
          ..: (( inject meta.certs.consul.agent ))
          ca_cert: (( grab meta.certs.consul.ca ))
          encrypt_keys:
          - (( vault meta.vault "/consul/encryption_key:current" ))