---
params:
  uaadb_user: (( vault meta.vault "/uaadb:user" ))
  uaadb_password: (( vault meta.vault "/uaadb:password" ))
  uaadb_scheme: mysql
  uaadb_port: 3306

  ccdb_user: (( vault meta.vault "/ccdb:user" ))
  ccdb_password: (( vault meta.vault "/ccdb:password" ))
  ccdb_scheme: mysql
  ccdb_port: 3306
  diegodb_user: (( vault meta.vault "/diegodb:user" ))
  diegodb_password: (( vault meta.vault "/diegdb:password" ))
  diegodb_scheme: mysql
  diegodb_port: 3306
  diegodb_connection_string: (( concat params.diegodb_user ":" params.diegodb_password "@tcp(" params.diegodb_host ":" params.diegodb_port ")/" params.diegodb_name ))
