---
instance_groups:
- (( delete "consul_etcd" ))
- (( merge ))
- name: nats
  jobs:
  - (( delete "consul_agent" ))

- name: api
  jobs:
  - (( delete "consul_agent" ))

- name: uaa
  jobs:
  - (( delete "consul_agent" ))

- name: doppler
  jobs:
  - (( delete "consul_agent" ))

- name: syslogger
  jobs:
  - (( delete "consul_agent" ))

- name: loggregator_trafficcontroller
  jobs:
  - (( delete "consul_agent" ))

- name: router
  jobs:
  - (( delete "consul_agent" ))

- name: bbs
  jobs:
  - (( delete "consul_agent" ))
  - (( merge ))
  - name: bbs
    release: diego
    properties:
      enable_consul_service_registration: false
      diego:
        bbs:
          skip_consul_lock: true
          detect_consul_cell_registrations: false
  - name: locket
    release: diego
    properties:
      enable_consul_service_registration: false

- name: diego
  jobs:
  - (( delete "consul_agent" ))
  - (( merge ))
  - name: auctioneer
    release: diego
    properties:
      enable_consul_service_registration: false
      diego:
        auctioneer:
          skip_consul_lock: true
          watcher:
            locket:
            skip_consul_lock: true
  - name: route_emitter
    release: diego
    properties:
      locks:
        consul:
          enabled: false
  - name: tps
    release: capi
    properties:
      capi:
        tps:
          watcher:
            skip_consul_lock: true

- name: cell
  jobs:
  - name: rep
    release: diego
    properties:
      enable_consul_service_registration: false

- name: access
  jobs:
  - (( delete "consul_agent" ))
  - (( merge ))
  - name: ssh_proxy
    properties:
      enable_consul_service_registration: false

- name: cell
  jobs:
  - (( delete "consul_agent" ))
  - (( merge ))
  - name: rep
    properties:
      enable_consul_service_registration: false

meta:
  statsd_injector:
    enable_consul_service_registration: false