---
params:
  uaadb_user: (( vault meta.vault "/uaadb:user" ))
  uaadb_password: (( vault meta.vault "/uaadb:password" ))
  uaadb_scheme: postgresql
  uaadb_port: 5432
  ccdb_user: (( vault meta.vault "/ccdb:user" ))
  ccdb_password: (( vault meta.vault "/ccdb:password" ))
  ccdb_scheme: postgres
  ccdb_port: 5432
  diegodb_user: (( vault meta.vault "/diegodb:user" ))
  diegodb_password: (( vault meta.vault "/diegdb:password" ))
  diegodb_scheme: postgres
  diegodb_port: 5432
  diegodb_connection_string: (( concat params.diegodb_scheme "://" params.diegodb_user ":" params.diegodb_password "@" params.diegodb_host ":" params.diegodb_port "/" params.diegodb_name ))
